name: Go build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, feat/deliverable3 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        cd app
        go build -v -o memoria

    - name: Test
      run: |
        cd app/test
        go test -v